### ISSUE TITLE
postgres Database CRD fails to install on older API-server CEL environments (optionalOldSelf: no matching overload for 'hasValue')

### ISSUE THREAD

**Issue by ronlevy1211** [crossplane-contrib/provider-sql#409]
### What happened?

The generated CRDs for the postgres `Database` resource (`databases.postgresql.sql.crossplane.io` and the v2 namespaced `databases.postgresql.sql.m.crossplane.io`) fail to install on Kubernetes API servers whose CEL environment does not honor `optionalOldSelf`. The API server rejects the CRD:

```
cannot establish control of object: CustomResourceDefinition
"databases.postgresql.sql.crossplane.io" is invalid:
...x-kubernetes-validations[0].rule: compilation failed:
ERROR found no matching overload for 'hasValue' applied to 'selfType...'
```

When this happens the provider's `ProviderRevision` cannot establish control and **provider-sql fails to install** on the affected cluster.

### The offending rule

Introduced in #343, the `strategy`-immutability validation on `DatabaseParameters` is generated with `optionalOldSelf=true`:

```
!oldSelf.hasValue() || ((!has(self.strategy) && !has(oldSelf.value().strategy))
 || (has(self.strategy) && has(oldSelf.value().strategy)
     && self.strategy == oldSelf.value().strategy))
```

`optionalOldSelf` (the `oldSelf.hasValue()` / `oldSelf.value()` form) requires a newer API-server CEL environment. Where it isn't honored, `oldSelf` is not wrapped as an optional, so `hasValue()`/`value()` have no matching overload and the CEL rule fails to compile — so the whole CRD is rejected.

### Works vs. fails

Same Kubernetes minor; differs only by the API-server (EKS platform) build:

| API server | Result |
|---|---|
| `v1.31.14-eks-8f14419` | installs fine |
| `v1.31.14-eks-0690643` | CRD rejected |
| `v1.30.14` (EKS) | CRD rejected |

The EKS platform build is provider-managed with no per-cluster ETA, so "wait for the newer build" isn't actionable for affected users.

### Proposed fix

The rule enforces simple immutability of `strategy`. Because it is a **transition rule** (it references `oldSelf`), it only runs on UPDATE, where `oldSelf` is always present — so `optionalOldSelf` is unnecessary. Replacing it with a plain presence-aware transition rule compiles on all Kubernetes >= 1.25:

```
(!has(self.strategy) && !has(oldSelf.strategy)) ||
(has(self.strategy) && has(oldSelf.strategy) && self.strategy == oldSelf.strategy)
```

One thing worth confirming from the #343 authors: `optionalOldSelf` also allows a rule to run at CREATE (no `oldSelf`). The "immutable after creation" intent only needs UPDATE enforcement, so a transition rule is correct — but flagging in case the rule was meant to also reject something at CREATE.

Happy to open a PR (fix ready).

### How can we reproduce it?

Apply the generated `Database` CRD to an API server whose CEL environment does not honor `optionalOldSelf` (e.g. EKS `v1.31.14-eks-0690643` or a 1.30.x cluster) with a server-side dry run; the apply fails with `compilation failed: ERROR found no matching overload for 'hasValue'`.

**Comment by ronlevy1211** [comment]
Closing - agreed with the discussion in #410 that it's not worth changing upstream for k8s versions that are on their way out. Leaving the analysis here for anyone who hits the same on older EKS control-plane builds; we're handling it downstream.
